// Convertly Studio's Video editing surface: a real upload, a real <video> element for
// scrubbing and playback (native controls, no fake preview), a draggable trim timeline for
// picking the exported range, and draggable text overlays. The overlay preview and the
// exported file are the same rendering path: at export time the overlays are drawn onto an
// offscreen canvas at the source video's real pixel resolution and burned into every frame
// of the trimmed range by the same FFmpeg WebAssembly engine every other video tool in this
// app already uses, so what is previewed is what comes out.
import { el, clear } from "../ui/dom";
import { createUploader } from "../ui/upload";
import { createProcessPanel } from "../ui/processPanel";
import { renderResultPanel } from "../ui/resultPanel";
import { exportStudioVideo, type TimedOverlayLayer } from "../lib/videoTools";
import { VIDEO_FILTER_PRESETS, videoFilterById } from "../lib/videoFilters";
import { STICKER_CATEGORIES, STICKER_CATEGORY_LABELS, stickersByCategory, type StickerCategory } from "../lib/stickerLibrary";
import { CAPTION_TEMPLATES, captionTemplateById, type CaptionTemplate } from "../lib/captionTemplates";
import type { CaptionWord } from "../lib/captions";
import type { DetectedKind } from "../lib/validate";
import { getUsageStatus, recordCompletedOperation } from "../lib/usageLimit";
import { usageLimitReachedPanel } from "../ui/usageBadge";

import "@fontsource/inter/700.css";
import "@fontsource/poppins/700.css";
import "@fontsource/anton/400.css";
import "@fontsource/bebas-neue/400.css";
import "@fontsource/caveat/700.css";

const ACCEPT: DetectedKind[] = ["mp4", "webm", "mov", "mkv", "avi"];
const INPUT_ACCEPT = "video/mp4,video/webm,video/quicktime,video/x-matroska,video/x-msvideo";

interface OverlayFont {
  id: string;
  label: string;
  family: string;
  canvasFamily: string;
}

const OVERLAY_FONTS: OverlayFont[] = [
  { id: "inter", label: "Inter", family: "Inter, sans-serif", canvasFamily: "Inter" },
  { id: "poppins", label: "Poppins", family: "Poppins, sans-serif", canvasFamily: "Poppins" },
  { id: "anton", label: "Anton", family: "Anton, sans-serif", canvasFamily: "Anton" },
  { id: "bebas", label: "Bebas Neue", family: "\"Bebas Neue\", sans-serif", canvasFamily: "Bebas Neue" },
  { id: "caveat", label: "Caveat", family: "Caveat, cursive", canvasFamily: "Caveat" },
];

interface TextOverlay {
  id: string;
  text: string;
  xPct: number; // center, 0 to 100, relative to the video's real width
  yPct: number; // center, 0 to 100, relative to the video's real height
  sizePct: number; // font size as a percent of the video's real width
  color: string;
  fontId: string;
  bold: boolean;
  kind?: "text" | "sticker" | "image"; // stickers are just emoji glyphs, images are an uploaded photo/asset; all three share the same overlay pipeline
  startMs: number; // when this overlay becomes visible, relative to the clip's own start (0)
  durationMs: number; // how long it stays visible after startMs
  imageSrc?: string; // data URL, image overlays only
  imageAspect?: number; // natural width/height, image overlays only, so the box keeps its shape as sizePct scales it
  entrance?: "none" | "fade" | "pop" | "bounce" | "slide-up"; // how this overlay animates in at startMs, burned into the real export, not just the live preview
  entranceDurationMs?: number;
  isCaption?: boolean; // auto-generated by the Captions component, so it can offer "clear all captions" without touching manual overlays
  templateId?: string; // which Caption Library template this caption was last given, captions only
  uppercase?: boolean;
  bgColor?: string; // a pill/box background behind the text, "" or undefined = none, captions only
  align?: "center" | "left" | "right";
  wordMode?: "none" | "type-on" | "word-highlight"; // how the words *within* this caption reveal over its own time window, captions only
  highlightColor?: string; // word-highlight only: color of the word currently being spoken
  words?: CaptionWord[]; // word-level timing within this caption, captions only, used by type-on/word-highlight
}

const ENTRANCE_OPTIONS: { id: NonNullable<TextOverlay["entrance"]>; label: string }[] = [
  { id: "none", label: "None" },
  { id: "fade", label: "Fade in" },
  { id: "pop", label: "Pop" },
  { id: "bounce", label: "Bounce" },
  { id: "slide-up", label: "Slide up" },
];

// Bottom-toolbar / "components" catalog for the video editor: a CapCut-style pattern where a
// row of icons at the bottom is the "home" of everything you can do to the clip, tapping one
// opens that tool in the side panel, and a back arrow returns to the same row. Design/image
// editing keeps its own Canva-style rail+flyout instead; this pattern is specific to Video
// (and, per the audio editor, deliberately NOT used there either).
type VideoComponentId = "trim" | "text" | "captions" | "image" | "stickers" | "filters" | "audio";
interface VideoComponentDef {
  id: VideoComponentId;
  label: string;
  desc: string;
  icon: string;
}
const VIDEO_COMPONENTS: VideoComponentDef[] = [
  {
    id: "trim",
    label: "Trim",
    desc: "Pick the range that gets exported.",
    icon: `<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M6 3v18M18 3v18"/><rect x="6" y="9" width="12" height="6" rx="1.5"/></svg>`,
  },
  {
    id: "text",
    label: "Text",
    desc: "Captions and text overlays burned into the frame.",
    icon: `<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M5 6h14M12 6v14"/></svg>`,
  },
  {
    id: "captions",
    label: "Captions",
    desc: "Auto-generate subtitles from the clip's own audio, right here, no upload to a server.",
    icon: `<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="2.5" y="5" width="19" height="14" rx="2.5"/><path d="M6 15h4M12 15h6M6 10.5h12"/></svg>`,
  },
  {
    id: "image",
    label: "Image",
    desc: "Overlay a photo or asset, and vectorize it if you like.",
    icon: `<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="3" y="4.5" width="18" height="15" rx="2"/><path d="M3 15l5-5 4 4 3-3 6 6"/><circle cx="8" cy="9" r="1.4"/></svg>`,
  },
  {
    id: "stickers",
    label: "Stickers",
    desc: "Drop an emoji sticker anywhere on the frame.",
    icon: `<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="12" cy="12" r="9"/><circle cx="9" cy="10" r="1"/><circle cx="15" cy="10" r="1"/><path d="M8 14.5c1.2 1.4 2.6 2 4 2s2.8-.6 4-2"/></svg>`,
  },
  {
    id: "filters",
    label: "Filters",
    desc: "Ready-made looks: black & white, vintage, vignette and more.",
    icon: `<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="9" cy="12" r="6"/><circle cx="15" cy="12" r="6"/></svg>`,
  },
  {
    id: "audio",
    label: "Audio",
    desc: "Adjust the clip's own audio volume.",
    icon: `<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M4 13v-2a8 8 0 0 1 16 0v2"/><rect x="2.5" y="12.5" width="4" height="6" rx="1.5"/><rect x="17.5" y="12.5" width="4" height="6" rx="1.5"/></svg>`,
  },
];

function uid(): string {
  return Math.random().toString(36).slice(2, 10);
}

function formatTime(sec: number): string {
  const s = Number.isFinite(sec) && sec > 0 ? sec : 0;
  const m = Math.floor(s / 60);
  const r = Math.floor(s % 60);
  return `${m}:${r.toString().padStart(2, "0")}`;
}

function fontById(id: string): OverlayFont {
  return OVERLAY_FONTS.find((f) => f.id === id) ?? OVERLAY_FONTS[0];
}

export interface StudioVideoToolOptions {
  onBack?: () => void;
  /** Used only by the guided tour: fetches this URL and opens it as the editor's clip the
   * moment the editor mounts, through the exact same openEditor() path a real upload takes. */
  autoLoadVideoUrl?: string;
  /** Used only by the guided tour: once the auto-loaded clip's metadata is ready, seeds a
   * couple of realistic caption overlays (with word-level timing, karaoke template applied)
   * without running real speech-to-text, so the Captions tour steps have real content to show
   * on a clip that has no actual speech to transcribe. */
  seedDemoCaptions?: boolean;
}

export function buildStudioVideoTool(opts: StudioVideoToolOptions): HTMLElement {
  const root = el("div", { class: "studio-video-tool" });
  // Lives outside openEditor() (which re-runs every time a new file is uploaded) so a fresh
  // upload can cancel the PREVIOUS file's animation loop before starting its own, rather than
  // stacking a second uncancellable loop on top of it.
  let outerAnimFrameId: number | null = null;

  const closeBtn = el("button", { type: "button", class: "studio-close-btn", "aria-label": "Back to Studio" });
  closeBtn.innerHTML = `<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 6l12 12M18 6L6 18"/></svg>`;
  closeBtn.addEventListener("click", () => opts.onBack?.());

  const titleEl = el("span", { class: "studio-editor-title" }, ["Video editor"]);
  const topBarSpacer = el("div", { class: "studio-topbar-spacer" });
  const exportBtn = el("button", { type: "button", class: "run-btn", style: "display:none", "data-tour": "video-export" }, ["Export video"]);

  const topBar = el("div", { class: "studio-editor-topbar" }, [
    ...(opts.onBack ? [closeBtn] : []),
    titleEl,
    topBarSpacer,
    exportBtn,
  ]);

  const bodyHost = el("div", { class: "studio-video-body" });
  root.append(topBar, bodyHost);

  // ---------------- Upload screen ----------------

  function renderUpload() {
    clear(bodyHost);
    const wrap = el("div", { class: "studio-video-upload" }, [
      el("h2", {}, ["Upload a video to edit"]),
      el("p", { class: "control-hint" }, [
        "Trim a range, drag captions or labels onto the frame, then export, all rendered by a real FFmpeg engine in this tab.",
      ]),
    ]);
    const uploader = createUploader({
      accept: ACCEPT,
      acceptLabel: "MP4, WebM, MOV, MKV, or AVI",
      inputAccept: INPUT_ACCEPT,
      onFileReady: (file) => openEditor(file),
    });
    wrap.appendChild(uploader.root);
    bodyHost.appendChild(wrap);
    exportBtn.style.display = "none";
  }

  // ---------------- Editor screen ----------------

  function openEditor(file: File) {
    if (outerAnimFrameId !== null) {
      cancelAnimationFrame(outerAnimFrameId);
      outerAnimFrameId = null;
    }
    exportBtn.style.display = "";
    clear(bodyHost);

    let duration = 0;
    let trimStart = 0;
    let trimEnd = 0;
    let overlays: TextOverlay[] = [];
    let selectedId: string | null = null;
    let filterPresetId = "none";
    let audioGainDb = 0;
    let activeComponent: VideoComponentId | null = null;
    let filterThumbUrl = "";
    let captionStatus: "idle" | "working" | "error" = "idle";
    let captionErrorMessage = "";

    const videoUrl = URL.createObjectURL(file);
    const videoEl = el("video", { src: videoUrl, controls: "", playsinline: "", class: "studio-video-el" }) as HTMLVideoElement;
    const overlayLayer = el("div", { class: "studio-video-overlay-layer" });
    const vignetteOverlay = el("div", { class: "studio-video-vignette-overlay" });
    const stage = el("div", { class: "studio-video-stage" }, [videoEl, vignetteOverlay, overlayLayer]);
    // The stage fills all the vertical room this wrap has to give (see CSS), sized to the
    // clip's own real aspect ratio, rather than being capped to a fixed pixel width that
    // leaves empty space on wide screens; the wrap centers it when the aspect ratio leaves
    // some width unused.
    const stageWrap = el("div", { class: "studio-video-stage-wrap" }, [stage]);

    function applyFilterPreview() {
      const preset = videoFilterById(filterPresetId);
      videoEl.style.filter = preset.cssFilter || "none";
      vignetteOverlay.style.display = preset.needsVignetteOverlay ? "block" : "none";
    }

    function applyAudioGainPreview() {
      // The browser's own <video> volume tops out at 1.0, so a positive dB boost can only be
      // previewed up to that ceiling; the real gain is still applied honestly at export time
      // via ffmpeg's volume filter, which isn't limited the same way.
      const linear = Math.pow(10, audioGainDb / 20);
      videoEl.volume = Math.max(0, Math.min(1, linear));
    }

    const filmstrip = el("div", { class: "studio-video-filmstrip" });
    const filmstripLoading = el("div", { class: "studio-video-filmstrip-loading" }, ["Generating frame preview..."]);
    const maskLeft = el("div", { class: "studio-video-trim-mask left" });
    const maskRight = el("div", { class: "studio-video-trim-mask right" });
    const trimRange = el("div", { class: "studio-video-trim-range" });
    const trimStartHandle = el("div", { class: "studio-video-trim-handle start", "aria-label": "Trim start" }, [
      el("span", { class: "studio-video-trim-grip" }),
    ]);
    const trimEndHandle = el("div", { class: "studio-video-trim-handle end", "aria-label": "Trim end" }, [
      el("span", { class: "studio-video-trim-grip" }),
    ]);
    const trimTrack = el("div", { class: "studio-video-trim-track", "data-tour": "video-timeline" }, [
      filmstrip,
      maskLeft,
      maskRight,
      trimRange,
      trimStartHandle,
      trimEndHandle,
      filmstripLoading,
    ]);
    const trimLabels = el("div", { class: "studio-video-trim-labels" }, [
      el("span", {}, ["0:00"]),
      el("span", { class: "studio-video-trim-readout" }, ["0:00 to 0:00"]),
      el("span", {}, ["0:00"]),
    ]);
    const overlayTracks = el("div", { class: "studio-video-overlay-tracks" });

    const addTextBtn = el("button", { type: "button", class: "studio-flyout-item" }, ["+ Add a text overlay"]);
    const overlayListHost = el("div", { class: "studio-video-overlay-list" });
    const propsHost = el("div", { class: "studio-video-overlay-props" });

    // ---------------- Components: a CapCut-style bottom toolbar plus a "home of all
    // components" grid, rather than one fixed side panel. Trim/Text/Stickers/Filters/Audio
    // each open into the same panel body; the back arrow returns to the grid. ----------------

    const panelBackBtn = el("button", { type: "button", class: "studio-comp-back", "aria-label": "Back to all components" }, []);
    panelBackBtn.innerHTML = `<svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="2"><path d="M15 5l-7 7 7 7"/></svg><span>All components</span>`;
    const panelTitle = el("span", { class: "studio-comp-title" }, ["Edit this clip"]);
    const panelHeader = el("div", { class: "studio-comp-header" }, [panelBackBtn, panelTitle]);
    const panelBody = el("div", { class: "studio-comp-body" });
    const sidePanel = el("div", { class: "studio-video-panel studio-comp-panel" }, [panelHeader, panelBody]);

    // The right-hand detail panel: only shown for components that have an actual library to
    // browse (Stickers, Filters), so it can hold the big visual grid without crowding the
    // left panel's controls and this clip's own overlay list.
    const detailTitle = el("span", { class: "studio-comp-title" }, ["Library"]);
    const detailHeader = el("div", { class: "studio-comp-header" }, [detailTitle]);
    const detailBody = el("div", { class: "studio-comp-body" });
    const detailPanel = el("div", { class: "studio-video-panel studio-video-detail-panel studio-comp-panel" }, [detailHeader, detailBody]);
    detailPanel.style.display = "none";

    const bottomToolbar = el("div", { class: "studio-comp-toolbar", "data-tour": "video-toolbar" });
    const toolbarButtons = new Map<VideoComponentId, HTMLElement>();
    for (const def of VIDEO_COMPONENTS) {
      const btn = el("button", { type: "button", class: "studio-comp-toolbar-btn", title: def.label }, []);
      const iconBox = el("span", { class: "studio-comp-toolbar-icon" }, []);
      iconBox.innerHTML = def.icon;
      btn.append(iconBox, el("span", { class: "studio-comp-toolbar-label" }, [def.label]));
      btn.setAttribute("data-tour", `comp-toolbar-${def.id}`);
      btn.addEventListener("click", () => openComponent(def.id));
      toolbarButtons.set(def.id, btn);
      bottomToolbar.appendChild(btn);
    }

    const homeGrid = el("div", { class: "studio-comp-grid" });
    for (const def of VIDEO_COMPONENTS) {
      const tile = el("button", { type: "button", class: "studio-comp-tile" }, []);
      const iconBox = el("span", { class: "studio-comp-tile-icon" }, []);
      iconBox.innerHTML = def.icon;
      tile.append(iconBox, el("span", { class: "studio-comp-tile-label" }, [def.label]), el("span", { class: "studio-comp-tile-desc" }, [def.desc]));
      tile.addEventListener("click", () => openComponent(def.id));
      homeGrid.appendChild(tile);
    }

    function buildTrimComponent(): HTMLElement {
      const resetBtn = el("button", { type: "button", class: "studio-icon-btn" }, ["Reset trim to full clip"]);
      resetBtn.addEventListener("click", () => {
        trimStart = 0;
        trimEnd = duration;
        videoEl.currentTime = 0;
        renderTrim();
      });
      return el("div", {}, [
        el("p", { class: "control-hint" }, ["Drag the two handles on the timeline below to pick what gets exported."]),
        resetBtn,
      ]);
    }

    function renderFilterLibraryInto(container: HTMLElement) {
      clear(container);
      const grid = el("div", { class: "studio-filter-grid" });
      for (const preset of VIDEO_FILTER_PRESETS) {
        const swatch = el("button", { type: "button", class: `studio-filter-swatch${preset.id === filterPresetId ? " active" : ""}` });
        const thumb = el("span", { class: "studio-filter-swatch-thumb" });
        thumb.style.filter = preset.cssFilter || "none";
        // A <video> blob URL can't be used as a CSS background-image (only actual images
        // render there), so this reuses one of the filmstrip's already-extracted frame
        // thumbnails (a real decoded PNG/JPEG data URL) instead of the raw video source.
        if (filterThumbUrl) thumb.style.backgroundImage = `url(${filterThumbUrl})`;
        swatch.append(thumb, el("span", { class: "studio-filter-swatch-label" }, [preset.label]));
        swatch.addEventListener("click", () => {
          filterPresetId = preset.id;
          applyFilterPreview();
          grid.querySelectorAll(".studio-filter-swatch").forEach((n) => n.classList.remove("active"));
          swatch.classList.add("active");
        });
        grid.appendChild(swatch);
      }
      container.appendChild(grid);
    }

    function buildFiltersComponent(): HTMLElement {
      return el("div", {}, [
        el("p", { class: "control-hint" }, ["Pick a ready-made look from the library on the right, burned into the export by the same FFmpeg engine, not just a CSS preview."]),
      ]);
    }

    function buildAudioComponent(): HTMLElement {
      const gainInput = el("input", { type: "range", min: "-20", max: "20", step: "1", value: String(audioGainDb) }) as HTMLInputElement;
      const gainReadout = el("span", { class: "studio-audio-readout" }, [`${audioGainDb > 0 ? "+" : ""}${audioGainDb} dB`]);
      gainInput.addEventListener("input", () => {
        audioGainDb = Number(gainInput.value);
        gainReadout.textContent = `${audioGainDb > 0 ? "+" : ""}${audioGainDb} dB`;
        applyAudioGainPreview();
      });
      return el("div", {}, [
        el("p", { class: "control-hint" }, ["Adjusts this clip's own audio track. A positive boost previews quieter than the real export can render (players can't play back louder than 100%)."]),
        el("label", { class: "studio-field" }, [el("span", {}, ["Gain"]), gainInput, gainReadout]),
      ]);
    }

    // A brief loading state for the same reason the Design editor has one: vectorizing an
    // image traces every path synchronously and can take a visible moment, so the stage shows
    // it is genuinely working rather than appearing frozen.
    let progressOverlayEl: HTMLElement | null = null;
    let progressLabelEl: HTMLElement | null = null;
    function showStageProgress(label: string, sublabel?: string) {
      if (!progressOverlayEl) {
        progressLabelEl = el("div", { class: "studio-progress-label" }, [label]);
        progressOverlayEl = el("div", { class: "studio-progress-overlay" }, [
          el("div", { class: "studio-progress-ring" }),
          progressLabelEl,
          ...(sublabel ? [el("div", { class: "studio-progress-sublabel" }, [sublabel])] : []),
        ]);
        stageWrap.appendChild(progressOverlayEl);
      } else if (progressLabelEl) {
        progressLabelEl.textContent = label;
      }
    }
    function hideStageProgress() {
      if (progressOverlayEl) {
        progressOverlayEl.remove();
        progressOverlayEl = null;
        progressLabelEl = null;
      }
    }

    const imageOverlayInput = el("input", { type: "file", accept: "image/png,image/jpeg,image/webp", class: "sr-only" }) as HTMLInputElement;
    imageOverlayInput.addEventListener("change", () => {
      const file = imageOverlayInput.files?.[0];
      if (file) addImageOverlay(file);
      imageOverlayInput.value = "";
    });

    function addImageOverlay(file: File) {
      const reader = new FileReader();
      reader.onload = () => {
        const src = String(reader.result);
        const img = new Image();
        img.onload = () => {
          const [startMs, durationMs] = defaultOverlayWindowMs();
          const ov: TextOverlay = {
            id: uid(),
            text: file.name.replace(/\.[a-z0-9]+$/i, "") || "Image",
            xPct: 50,
            yPct: 50,
            sizePct: 30,
            color: "#ffffff",
            fontId: "inter",
            bold: false,
            kind: "image",
            imageSrc: src,
            imageAspect: img.width / Math.max(1, img.height),
            startMs,
            durationMs,
          };
          overlays.push(ov);
          selectOverlay(ov.id);
        };
        img.src = src;
      };
      reader.readAsDataURL(file);
    }

    // Traces an image overlay into an SVG (the same tracing engine as the standalone Vectorize
    // tool and the Design editor's own Vectorize button) and swaps it in place, keeping the
    // overlay's own position, size and timing untouched.
    async function vectorizeOverlayImage(ov: TextOverlay, statusBtn?: HTMLElement) {
      if (ov.kind !== "image" || !ov.imageSrc) return;
      const btn = statusBtn as HTMLButtonElement | undefined;
      const originalLabel = btn?.textContent ?? "Vectorize";
      if (btn) {
        btn.textContent = "Vectorizing...";
        btn.disabled = true;
      }
      showStageProgress("Tracing image into vector paths...", "This can take a few seconds on larger photos.");
      try {
        const { vectorizeImage } = await import("../lib/vectorize");
        const srcBlob = await fetch(ov.imageSrc).then((r) => r.blob());
        const file = new File([srcBlob], "image.png", { type: srcBlob.type || "image/png" });
        const result = await vectorizeImage(file, { colorCount: 16, smoothing: 1, noiseReduction: 4, preserveCorners: true });
        showStageProgress("Finishing up...");
        const svgDataUrl = `data:image/svg+xml;base64,${btoa(unescape(encodeURIComponent(result.svg)))}`;
        const img = new Image();
        await new Promise<void>((resolve, reject) => {
          img.onload = () => resolve();
          img.onerror = () => reject(new Error("Could not load the vectorized image."));
          img.src = svgDataUrl;
        });
        ov.imageSrc = svgDataUrl;
        ov.imageAspect = img.width / Math.max(1, img.height);
        renderOverlayLayer();
        renderProps();
      } catch {
        if (btn) btn.textContent = "Couldn't vectorize, try again";
      } finally {
        hideStageProgress();
        if (btn) {
          btn.disabled = false;
          if (btn.textContent === "Vectorizing...") btn.textContent = originalLabel;
        }
      }
    }

    function buildImageComponent(): HTMLElement {
      const uploadBtn = el("button", { type: "button", class: "studio-flyout-item" }, ["+ Upload an image"]);
      uploadBtn.addEventListener("click", () => imageOverlayInput.click());
      return el("div", {}, [
        el("p", { class: "control-hint" }, ["Add a photo or asset on top of the frame, drag it into place, then vectorize it right here if you want a clean traced look."]),
        uploadBtn,
        imageOverlayInput,
        overlayListHost,
        propsHost,
      ]);
    }

    // ---------------- Captions: Auto Caption / Caption Library / Captions / Transcript ----------------

    let captionSubTab: "auto" | "library" | "captions" | "transcript" = "auto";
    let captionApplyScope: "all" | "selected" = "all";
    let lastUsedTemplateId = "clean-fade";

    /** Gives one caption overlay a template's full look in one shot: font, case, color, word
     * animation, position, and entrance, all burned into the real export (see buildOverlayPngs),
     * not just a live-preview skin. Still fully editable afterward, one field at a time, like
     * any other overlay. */
    function applyCaptionTemplate(ov: TextOverlay, tpl: CaptionTemplate) {
      ov.templateId = tpl.id;
      ov.fontId = tpl.fontId;
      ov.bold = tpl.bold;
      ov.uppercase = tpl.uppercase;
      ov.color = tpl.color;
      ov.highlightColor = tpl.highlightColor;
      ov.bgColor = tpl.bgColor;
      ov.sizePct = tpl.sizePct;
      ov.yPct = tpl.yPct;
      ov.align = tpl.align;
      ov.xPct = tpl.align === "left" ? 8 : tpl.align === "right" ? 92 : 50;
      ov.entrance = tpl.animation;
      ov.entranceDurationMs = tpl.animation === "pop" || tpl.animation === "bounce" ? 400 : 300;
      ov.wordMode = tpl.wordMode;
      lastUsedTemplateId = tpl.id;
    }

    // Auto-generates one caption overlay per transcribed phrase, using the clip's own audio,
    // real speech-to-text (see lib/captions.ts), never a stub or placeholder. Runs entirely in
    // the browser: the first use downloads the speech model once (cached by the browser after
    // that), and nothing about the person's video or audio ever leaves the tab. Word-level
    // timing comes back with every phrase, so a word-highlight or typewriter template can track
    // the speaker's actual words rather than just the phrase as a whole.
    async function autoGenerateCaptions() {
      if (captionStatus === "working") return;
      captionStatus = "working";
      renderCaptionsStatus();
      showStageProgress("Loading speech model...", "First use downloads it once; it's cached after that.");
      try {
        const { transcribeVideoToCaptions } = await import("../lib/captions");
        const chunks = await transcribeVideoToCaptions(file, (p) => {
          showStageProgress(
            p.phase === "Transcribing" ? "Transcribing speech..." : p.phase === "Decoding audio" ? "Decoding audio..." : "Loading speech model...",
            typeof p.ratio === "number" ? `${Math.round(p.ratio * 100)}%` : undefined
          );
        });
        if (chunks.length === 0) {
          captionStatus = "error";
          captionErrorMessage = "Couldn't find any speech in this clip's audio.";
        } else {
          const tpl = captionTemplateById(lastUsedTemplateId);
          for (const c of chunks) {
            const ov: TextOverlay = {
              id: uid(),
              text: c.text,
              xPct: 50,
              yPct: 88,
              sizePct: 4.5,
              color: "#ffffff",
              fontId: "anton",
              bold: true,
              kind: "text",
              isCaption: true,
              words: c.words,
              startMs: Math.max(0, c.startSec * 1000),
              durationMs: Math.max(300, (c.endSec - c.startSec) * 1000),
            };
            applyCaptionTemplate(ov, tpl);
            overlays.push(ov);
          }
          captionStatus = "idle";
          captionSubTab = "captions";
          renderOverlayLayer();
          renderOverlayList();
          renderOverlayTracks();
          renderComponentPanel();
        }
      } catch (err) {
        captionStatus = "error";
        captionErrorMessage = err instanceof Error ? err.message : "Something went wrong transcribing this clip.";
        console.error("Auto-captioning failed:", err);
      } finally {
        hideStageProgress();
        renderCaptionsStatus();
      }
    }

    let captionsStatusHost = el("div", { class: "control-hint" });
    function renderCaptionsStatus() {
      clear(captionsStatusHost);
      if (captionStatus === "working") {
        captionsStatusHost.appendChild(el("p", { class: "control-hint" }, ["Working on it, this can take a little while the first time..."]));
      } else if (captionStatus === "error") {
        captionsStatusHost.appendChild(el("div", { class: "validation-error" }, [captionErrorMessage]));
      }
      const captionCount = overlays.filter((o) => o.isCaption).length;
      if (captionCount > 0) {
        captionsStatusHost.appendChild(
          el("p", { class: "control-hint" }, [`${captionCount} caption${captionCount === 1 ? "" : "s"} on this clip.`])
        );
      }
    }

    function clearAllCaptions() {
      overlays = overlays.filter((o) => !o.isCaption);
      if (selectedId && !overlays.some((o) => o.id === selectedId)) selectedId = null;
      renderOverlayLayer();
      renderOverlayList();
      renderProps();
      renderOverlayTracks();
      renderCaptionsStatus();
    }

    function buildAutoCaptionTab(): HTMLElement {
      const genBtn = el("button", { type: "button", class: "run-btn" }, [
        overlays.some((o) => o.isCaption) ? "Re-generate captions" : "Auto-generate captions",
      ]);
      genBtn.addEventListener("click", () => void autoGenerateCaptions());
      const clearBtn = el("button", { type: "button", class: "studio-icon-btn" }, ["Clear all captions"]);
      clearBtn.addEventListener("click", clearAllCaptions);
      renderCaptionsStatus();
      return el("div", {}, [
        el("p", { class: "control-hint" }, [
          "Transcribes this clip's own audio into timed captions, right here in the browser, no upload to a server. Words are grouped into short, natural caption phrases with their own timing, ready for any template in the Caption Library.",
        ]),
        genBtn,
        clearBtn,
        captionsStatusHost,
      ]);
    }

    /** A small, self-contained CSS animation loop showing what a template's entrance actually
     * looks like, so someone can tell templates apart before applying one, not just read their
     * names. Runs on its own CSS animation, independent of any real overlay or the video's own
     * playhead. */
    function buildTemplatePreview(tpl: CaptionTemplate): HTMLElement {
      const font = fontById(tpl.fontId);
      const label = tpl.uppercase ? "YOUR CAPTION" : "Your caption";
      const stageEl = el("div", { class: "studio-caption-preview-stage" });
      const box = el(
        "span",
        {
          class: `studio-caption-preview-box studio-caption-anim-${tpl.animation}${tpl.wordMode !== "none" ? ` studio-caption-word-${tpl.wordMode}` : ""}`,
        },
        tpl.wordMode === "word-highlight"
          ? label.split(" ").map((w, i) =>
              el("span", { class: i === 1 ? "studio-caption-preview-hl" : "", style: i === 1 ? `color:${tpl.highlightColor}` : "" }, [`${w} `])
            )
          : [label]
      );
      box.style.fontFamily = font.family;
      box.style.fontWeight = tpl.bold ? "700" : "400";
      box.style.color = tpl.color;
      if (tpl.bgColor) {
        box.style.background = tpl.bgColor;
        box.style.padding = "0.25em 0.6em";
        box.style.borderRadius = "0.4em";
      }
      stageEl.appendChild(box);
      return stageEl;
    }

    function buildCaptionLibraryTab(): HTMLElement {
      const scopeRow = el("div", { class: "studio-field-row studio-field-row-wrap" }, [
        el("button", { type: "button", class: `studio-toggle-btn${captionApplyScope === "all" ? " active" : ""}` }, [
          "Apply to all captions",
        ]),
        el("button", { type: "button", class: `studio-toggle-btn${captionApplyScope === "selected" ? " active" : ""}` }, [
          "Apply to this caption only",
        ]),
      ]);
      const [allBtn, selectedBtn] = Array.from(scopeRow.children) as HTMLButtonElement[];
      allBtn.addEventListener("click", () => {
        captionApplyScope = "all";
        allBtn.classList.add("active");
        selectedBtn.classList.remove("active");
      });
      selectedBtn.addEventListener("click", () => {
        captionApplyScope = "selected";
        selectedBtn.classList.add("active");
        allBtn.classList.remove("active");
      });

      const grid = el("div", { class: "studio-caption-template-grid" });
      for (const tpl of CAPTION_TEMPLATES) {
        const card = el("button", { type: "button", class: "studio-caption-template-card" }, [
          buildTemplatePreview(tpl),
          el("span", { class: "studio-caption-template-label" }, [tpl.label]),
          el("span", { class: "studio-caption-template-desc" }, [tpl.desc]),
        ]);
        card.addEventListener("click", () => {
          const targets =
            captionApplyScope === "all"
              ? overlays.filter((o) => o.isCaption)
              : overlays.filter((o) => o.id === selectedId && o.isCaption);
          if (targets.length === 0) {
            lastUsedTemplateId = tpl.id;
            return;
          }
          for (const ov of targets) applyCaptionTemplate(ov, tpl);
          renderOverlayLayer();
          renderProps();
        });
        grid.appendChild(card);
      }
      return el("div", {}, [
        el("p", { class: "control-hint" }, [
          "Pick a look for your captions. New captions from Auto Caption use whichever template you applied most recently.",
        ]),
        scopeRow,
        grid,
      ]);
    }

    function buildCaptionsListTab(): HTMLElement {
      return el("div", {}, [
        el("p", { class: "control-hint" }, ["Select a caption to edit its text, timing, position, or style. Drag it directly on the video to reposition it."]),
        overlayListHost,
        propsHost,
      ]);
    }

    /** A full, chronological, plain-text view of every caption on the clip, each one editable
     * right there, exactly the "correct transcription mistakes" workflow professional caption
     * tools offer, without hunting through the overlay list one at a time. */
    function buildTranscriptTab(): HTMLElement {
      const captions = overlays.filter((o) => o.isCaption).slice().sort((a, b) => a.startMs - b.startMs);
      if (captions.length === 0) {
        return el("div", {}, [el("p", { class: "control-hint" }, ["No transcript yet, run Auto Caption first."])]);
      }
      const list = el("div", { class: "studio-transcript-list" });
      for (const ov of captions) {
        const timeLabel = el("span", { class: "studio-transcript-time" }, [`${formatTime(ov.startMs / 1000)}`]);
        const textArea = el("textarea", { class: "studio-field-input studio-transcript-line", rows: "1" }) as HTMLTextAreaElement;
        textArea.value = ov.text;
        textArea.addEventListener("input", () => {
          ov.text = textArea.value;
          // Free-typed corrections can no longer be trusted to match the original per-word
          // timing, so this clears it rather than silently displaying stale word highlights.
          ov.words = undefined;
          renderOverlayLayer();
          renderOverlayList();
        });
        const jumpBtn = el("button", { type: "button", class: "studio-icon-btn studio-transcript-jump", title: "Jump to this caption" }, ["Jump"]);
        jumpBtn.addEventListener("click", () => {
          videoEl.currentTime = ov.startMs / 1000;
          selectOverlay(ov.id);
        });
        list.appendChild(el("div", { class: "studio-transcript-row" }, [timeLabel, textArea, jumpBtn]));
      }
      return el("div", {}, [
        el("p", { class: "control-hint" }, ["Every caption on this clip, in order. Fix a transcription mistake here or in the Captions tab, whichever is faster."]),
        list,
      ]);
    }

    function buildCaptionsComponent(): HTMLElement {
      const tabs: { id: typeof captionSubTab; label: string }[] = [
        { id: "auto", label: "Auto Caption" },
        { id: "captions", label: "Captions" },
        { id: "library", label: "Caption Library" },
        { id: "transcript", label: "Transcript" },
      ];
      const tabBar = el("div", { class: "studio-caption-subtabs" });
      const bodyHost2 = el("div", { class: "studio-caption-subtab-body" });
      function renderSub() {
        clear(tabBar);
        for (const t of tabs) {
          const btn = el("button", { type: "button", class: `studio-caption-subtab-btn${t.id === captionSubTab ? " active" : ""}` }, [t.label]);
          btn.addEventListener("click", () => {
            captionSubTab = t.id;
            renderSub();
          });
          tabBar.appendChild(btn);
        }
        clear(bodyHost2);
        if (captionSubTab === "auto") bodyHost2.appendChild(buildAutoCaptionTab());
        else if (captionSubTab === "library") bodyHost2.appendChild(buildCaptionLibraryTab());
        else if (captionSubTab === "captions") bodyHost2.appendChild(buildCaptionsListTab());
        else bodyHost2.appendChild(buildTranscriptTab());
      }
      renderSub();
      return el("div", { class: "studio-caption-tabs" }, [tabBar, bodyHost2]);
    }

    function addStickerOverlay(glyph: string) {
      const [startMs, durationMs] = defaultOverlayWindowMs();
      const ov: TextOverlay = {
        id: uid(),
        text: glyph,
        xPct: 50,
        yPct: 50,
        sizePct: 10,
        color: "#ffffff",
        fontId: "inter",
        bold: false,
        kind: "sticker",
        startMs,
        durationMs,
      };
      overlays.push(ov);
      selectOverlay(ov.id);
    }

    // The library grid lives in the right-hand detail panel (see renderStickerLibraryInto);
    // this left-side component just carries the hint plus this clip's placed overlays, so the
    // filter state needs to persist across re-renders of either side.
    let stickerCategory: StickerCategory | "all" = "all";
    let stickerQuery = "";

    function renderStickerLibraryInto(container: HTMLElement) {
      clear(container);
      const searchInput = el("input", {
        type: "search",
        placeholder: "Search stickers",
        class: "studio-icon-search",
        value: stickerQuery,
      }) as HTMLInputElement;
      const catBar = el("div", { class: "studio-sfx-categories studio-sticker-categories" });
      const grid = el("div", { class: "studio-sticker-grid" });

      function renderCatBar() {
        clear(catBar);
        const pills: { id: StickerCategory | "all"; label: string }[] = [
          { id: "all", label: "All" },
          ...STICKER_CATEGORIES.map((c) => ({ id: c, label: STICKER_CATEGORY_LABELS[c] })),
        ];
        for (const p of pills) {
          const pill = el("button", { type: "button", class: `studio-sfx-cat-pill${p.id === stickerCategory ? " active" : ""}` }, [p.label]);
          pill.addEventListener("click", () => {
            stickerCategory = p.id;
            renderCatBar();
            renderGrid();
          });
          catBar.appendChild(pill);
        }
      }
      function renderGrid() {
        clear(grid);
        const q = stickerQuery.trim().toLowerCase();
        const base = stickersByCategory(stickerCategory);
        const list = q ? base.filter((s) => s.label.toLowerCase().includes(q)) : base;
        if (list.length === 0) {
          grid.appendChild(el("div", { class: "control-hint" }, ["No stickers match that search."]));
          return;
        }
        for (const s of list) {
          const btn = el("button", { type: "button", class: "studio-sticker-btn", title: s.label }, [s.glyph]);
          btn.addEventListener("click", () => addStickerOverlay(s.glyph));
          grid.appendChild(btn);
        }
      }
      searchInput.addEventListener("input", () => {
        stickerQuery = searchInput.value;
        renderGrid();
      });
      renderCatBar();
      renderGrid();
      container.append(searchInput, catBar, grid);
    }

    function buildStickersComponent(): HTMLElement {
      return el("div", {}, [
        el("p", { class: "control-hint" }, ["Pick a sticker from the library on the right to drop it in the middle of the frame, then drag it into place."]),
        el("h4", {}, ["On this clip"]),
        overlayListHost,
        propsHost,
      ]);
    }

    function buildTextComponent(): HTMLElement {
      return el("div", {}, [addTextBtn, overlayListHost, propsHost]);
    }

    function renderComponentPanel() {
      clear(panelBody);
      clear(detailBody);
      detailPanel.style.display = "none";
      if (!activeComponent) {
        panelBackBtn.style.display = "none";
        panelTitle.textContent = "Edit this clip";
        panelBody.appendChild(homeGrid);
        toolbarButtons.forEach((btn) => btn.classList.remove("active"));
        return;
      }
      panelBackBtn.style.display = "";
      const def = VIDEO_COMPONENTS.find((c) => c.id === activeComponent)!;
      panelTitle.textContent = def.label;
      toolbarButtons.forEach((btn, id) => btn.classList.toggle("active", id === activeComponent));
      if (activeComponent === "trim") panelBody.appendChild(buildTrimComponent());
      else if (activeComponent === "text") panelBody.appendChild(buildTextComponent());
      else if (activeComponent === "captions") panelBody.appendChild(buildCaptionsComponent());
      else if (activeComponent === "image") panelBody.appendChild(buildImageComponent());
      else if (activeComponent === "stickers") {
        panelBody.appendChild(buildStickersComponent());
        detailTitle.textContent = "Sticker library";
        detailPanel.style.display = "";
        renderStickerLibraryInto(detailBody);
      } else if (activeComponent === "filters") {
        panelBody.appendChild(buildFiltersComponent());
        detailTitle.textContent = "Filter library";
        detailPanel.style.display = "";
        renderFilterLibraryInto(detailBody);
      } else if (activeComponent === "audio") panelBody.appendChild(buildAudioComponent());
      // The text/props hosts are shared between the Text, Captions, Image and Stickers
      // components (a caption and a sticker are both just an overlay, edited through the same
      // list/props UI), so whichever one is open, keep them in sync with the current selection.
      if (activeComponent === "text" || activeComponent === "captions" || activeComponent === "image" || activeComponent === "stickers") {
        renderOverlayList();
        renderProps();
      }
    }

    function openComponent(id: VideoComponentId) {
      activeComponent = id;
      renderComponentPanel();
    }

    panelBackBtn.addEventListener("click", () => {
      activeComponent = null;
      renderComponentPanel();
    });

    const editorLayout = el("div", { class: "studio-video-editor-layout" }, [
      sidePanel,
      el("div", { class: "studio-video-main" }, [stageWrap, trimTrack, overlayTracks, trimLabels]),
      detailPanel,
    ]);

    const resultHost = el("div");
    bodyHost.append(editorLayout, bottomToolbar, resultHost);
    renderComponentPanel();

    videoEl.addEventListener("loadedmetadata", () => {
      duration = videoEl.duration || 0;
      trimStart = 0;
      trimEnd = duration;
      // Size the stage to the clip's own real aspect ratio (rather than a fixed placeholder),
      // so it fills the available height with no letterboxing and overlay percentages stay
      // pixel-accurate between this preview and the real export.
      const w = videoEl.videoWidth || 16;
      const h = videoEl.videoHeight || 9;
      stage.style.aspectRatio = `${w} / ${h}`;
      renderTrim();
      void buildFilmstrip();
      if (opts.seedDemoCaptions && !overlays.some((o) => o.isCaption)) seedDemoCaptions();
    });

    /** The guided tour's stand-in for real Auto Caption: the bundled demo clip has no real
     * speech, so this hand-builds a couple of realistic, word-timed caption overlays and
     * applies the karaoke template to them, the exact same overlay objects a real transcription
     * would produce, so every later Captions/Caption Library/Transcript step has genuine
     * content to show rather than an empty state. */
    function seedDemoCaptions() {
      const lines = ["Welcome to Convertly Studio", "Edit video right in your browser", "Captions in one click"];
      const span = Math.max(1, duration) / lines.length;
      const tpl = captionTemplateById("karaoke-highlight");
      for (let i = 0; i < lines.length; i++) {
        const startSec = i * span + 0.2;
        const endSec = startSec + Math.min(span - 0.3, 2.2);
        const words = lines[i].split(" ").map((w, wi, arr) => {
          const per = (endSec - startSec) / arr.length;
          return { text: w, startSec: startSec + wi * per, endSec: startSec + (wi + 1) * per };
        });
        const ov: TextOverlay = {
          id: uid(),
          text: lines[i],
          xPct: 50,
          yPct: 82,
          sizePct: 5,
          color: "#ffffff",
          fontId: "anton",
          bold: true,
          kind: "text",
          isCaption: true,
          words,
          startMs: startSec * 1000,
          durationMs: (endSec - startSec) * 1000,
        };
        applyCaptionTemplate(ov, tpl);
        overlays.push(ov);
      }
      renderOverlayLayer();
      renderOverlayList();
      renderOverlayTracks();
    }

    /** Runs continuously during playback (and on every scrub), so an overlay's visibility in
     * the live preview tracks the playhead without rebuilding every overlay box on each tick
     * (rebuilding mid-drag would detach the very node a drag is holding, the exact bug already
     * fixed once for selection above). */
    function syncOverlayVisibility() {
      const nowMs = videoEl.currentTime * 1000;
      overlayLayer.querySelectorAll(".studio-video-overlay-box").forEach((node) => {
        const id = node.getAttribute("data-overlay-id");
        const ov = overlays.find((o) => o.id === id);
        if (!ov) return;
        const boxEl = node as HTMLElement;
        boxEl.style.display = nowMs >= ov.startMs && nowMs <= ov.startMs + ov.durationMs ? "" : "none";
        applyOverlayAnimation(boxEl, ov, nowMs);
        // A word-highlight/type-on caption's own content changes continuously as the clip
        // plays, not just its opacity/position, so this rebuilds just that one box's children
        // each tick rather than re-rendering the whole overlay layer (which would detach any
        // box mid-drag).
        if (ov.wordMode && ov.wordMode !== "none" && !(ov.kind === "image")) {
          clear(boxEl);
          for (const node of buildCaptionContent(ov, nowMs)) boxEl.appendChild(typeof node === "string" ? document.createTextNode(node) : node);
        }
      });
    }
    videoEl.addEventListener("timeupdate", syncOverlayVisibility);

    // A smooth entrance animation (a few hundred ms) needs finer-grained updates than
    // "timeupdate" alone provides (that event fires only a few times a second), so this ticks
    // every animation frame instead, but only while the editor is actually the visible view
    // (offsetParent is null once this component's ancestor is hidden by the app's own view
    // switching), so it costs nothing once someone has navigated away from this editor.
    function animTick() {
      if (videoEl.offsetParent !== null) syncOverlayVisibility();
      outerAnimFrameId = requestAnimationFrame(animTick);
    }
    outerAnimFrameId = requestAnimationFrame(animTick);

    // ---------------- Filmstrip (real extracted frames, not a flat color bar) ----------------

    async function buildFilmstrip() {
      if (duration <= 0) return;
      clear(filmstrip);
      filmstripLoading.style.display = "flex";
      const wasPlaying = !videoEl.paused;
      videoEl.pause();
      const resumeTime = videoEl.currentTime;

      const trackWidth = trimTrack.getBoundingClientRect().width || 760;
      const tileWidth = 84;
      const count = Math.max(6, Math.min(16, Math.round(trackWidth / tileWidth)));

      const canvas = document.createElement("canvas");
      const aspect = (videoEl.videoWidth || 16) / (videoEl.videoHeight || 9);
      canvas.width = 160;
      canvas.height = Math.round(160 / aspect);
      const ctx = canvas.getContext("2d");

      const seekTo = (t: number): Promise<void> =>
        new Promise((resolve) => {
          const onSeeked = () => {
            videoEl.removeEventListener("seeked", onSeeked);
            resolve();
          };
          videoEl.addEventListener("seeked", onSeeked);
          videoEl.currentTime = t;
        });

      for (let i = 0; i < count; i++) {
        const t = Math.min(duration - 0.05, Math.max(0, ((i + 0.5) / count) * duration));
        try {
          await seekTo(t);
          if (ctx) ctx.drawImage(videoEl, 0, 0, canvas.width, canvas.height);
          const dataUrl = canvas.toDataURL("image/jpeg", 0.6);
          const img = el("img", { class: "studio-video-filmstrip-tile", alt: "" }) as HTMLImageElement;
          img.src = dataUrl;
          filmstrip.appendChild(img);
          // The filter swatches need one representative real frame too (a <video> blob URL
          // can't be used as a CSS background-image), so this reuses the middle filmstrip
          // tile already decoded here rather than seeking again just for that.
          if (i === Math.floor(count / 2)) filterThumbUrl = dataUrl;
        } catch {
          // A frame that fails to decode just leaves a gap tile rather than breaking the whole strip.
        }
      }

      await seekTo(resumeTime);
      if (wasPlaying) void videoEl.play().catch(() => {});
      filmstripLoading.style.display = "none";
    }

    // ---------------- Trim track (drag to pick the exported range) ----------------

    function pctFromClientX(clientX: number): number {
      const rect = trimTrack.getBoundingClientRect();
      if (rect.width === 0) return 0;
      return Math.max(0, Math.min(100, ((clientX - rect.left) / rect.width) * 100));
    }

    function renderTrim() {
      if (duration <= 0) return;
      const startPct = (trimStart / duration) * 100;
      const endPct = (trimEnd / duration) * 100;
      trimStartHandle.style.left = `${startPct}%`;
      trimEndHandle.style.left = `${endPct}%`;
      trimRange.style.left = `${startPct}%`;
      trimRange.style.width = `${Math.max(0, endPct - startPct)}%`;
      // The parts of the filmstrip outside the selected range are dimmed, matching how a
      // real timeline shows what will and won't make it into the export.
      maskLeft.style.width = `${startPct}%`;
      maskRight.style.width = `${100 - endPct}%`;
      const readout = trimLabels.querySelector(".studio-video-trim-readout");
      if (readout) readout.textContent = `${formatTime(trimStart)} to ${formatTime(trimEnd)} (${formatTime(trimEnd - trimStart)})`;
      renderOverlayTracks();
    }

    /** A CapCut-style row per text/sticker overlay under the filmstrip: each overlay is its own
     * track with its own clip bar, positioned and sized by that overlay's own startMs/durationMs
     * against the clip's full duration (not the trim window, which is a separate, shared
     * control above). The clip's body drags to move the whole window, and its left/right edges
     * each drag independently, one to change when it starts, the other how long it lasts,
     * exactly the "drag the start, drag the duration, independently, per element" timeline the
     * video editor was missing. */
    function renderOverlayTracks() {
      clear(overlayTracks);
      if (duration <= 0 || overlays.length === 0) return;
      const totalMs = duration * 1000;
      for (const ov of overlays) {
        const row = el("div", { class: `studio-video-layer-row${ov.id === selectedId ? " active" : ""}`, "data-overlay-id": ov.id });
        const clip = el("div", { class: "studio-video-layer-clip studio-video-overlay-clip" }, [
          el("span", { class: "studio-video-overlay-clip-handle studio-video-overlay-clip-handle-start" }),
          el("span", { class: "studio-video-overlay-clip-label" }, [ov.text || (ov.kind === "sticker" ? "Sticker" : "Text")]),
          el("span", { class: "studio-video-overlay-clip-handle studio-video-overlay-clip-handle-end" }),
        ]);
        const startHandle = clip.querySelector(".studio-video-overlay-clip-handle-start") as HTMLElement;
        const endHandle = clip.querySelector(".studio-video-overlay-clip-handle-end") as HTMLElement;

        function paint() {
          const leftPct = (ov.startMs / totalMs) * 100;
          const widthPct = (ov.durationMs / totalMs) * 100;
          clip.style.left = `${leftPct}%`;
          clip.style.width = `${Math.max(0.5, widthPct)}%`;
        }
        paint();

        clip.addEventListener("click", (e) => {
          // A click that lands on a handle is the tail end of a drag, not a plain select. The
          // browser also fires a plain "click" right after any drag's pointerup (native click
          // detection has no movement threshold), so this has to stay a non-destructive
          // selection update too, not a full renderOverlayTracks() rebuild, or it would detach
          // the very clip elements a drag just finished touching.
          if (e.target === startHandle || e.target === endHandle) return;
          selectOverlayInPlace(ov.id);
        });

        // Move the whole clip: both edges shift together, duration stays fixed.
        clip.addEventListener("pointerdown", (e) => {
          if (e.target === startHandle || e.target === endHandle) return;
          e.preventDefault();
          selectOverlayInPlace(ov.id);
          (clip as HTMLElement).setPointerCapture(e.pointerId);
          const trackWidth = overlayTracks.getBoundingClientRect().width || 1;
          const startX = e.clientX;
          const originStartMs = ov.startMs;
          const onMove = (ev: PointerEvent) => {
            const deltaMs = ((ev.clientX - startX) / trackWidth) * totalMs;
            const maxStart = Math.max(0, totalMs - ov.durationMs);
            ov.startMs = Math.max(0, Math.min(maxStart, originStartMs + deltaMs));
            paint();
            renderOverlayLayer();
          };
          const onUp = () => {
            window.removeEventListener("pointermove", onMove);
            window.removeEventListener("pointerup", onUp);
          };
          window.addEventListener("pointermove", onMove);
          window.addEventListener("pointerup", onUp);
        });

        // Drag the start edge: changes when it begins, keeps its own end fixed.
        startHandle.addEventListener("pointerdown", (e) => {
          e.preventDefault();
          e.stopPropagation();
          selectOverlayInPlace(ov.id);
          startHandle.setPointerCapture(e.pointerId);
          const trackWidth = overlayTracks.getBoundingClientRect().width || 1;
          const fixedEndMs = ov.startMs + ov.durationMs;
          const onMove = (ev: PointerEvent) => {
            const rect = overlayTracks.getBoundingClientRect();
            const pct = Math.max(0, Math.min(1, (ev.clientX - rect.left) / trackWidth));
            const newStart = Math.min(fixedEndMs - 200, Math.max(0, pct * totalMs));
            ov.startMs = newStart;
            ov.durationMs = fixedEndMs - newStart;
            paint();
            renderOverlayLayer();
          };
          const onUp = () => {
            window.removeEventListener("pointermove", onMove);
            window.removeEventListener("pointerup", onUp);
          };
          window.addEventListener("pointermove", onMove);
          window.addEventListener("pointerup", onUp);
        });

        // Drag the end edge: changes how long it lasts, keeps its own start fixed.
        endHandle.addEventListener("pointerdown", (e) => {
          e.preventDefault();
          e.stopPropagation();
          selectOverlayInPlace(ov.id);
          endHandle.setPointerCapture(e.pointerId);
          const trackWidth = overlayTracks.getBoundingClientRect().width || 1;
          const fixedStartMs = ov.startMs;
          const onMove = (ev: PointerEvent) => {
            const rect = overlayTracks.getBoundingClientRect();
            const pct = Math.max(0, Math.min(1, (ev.clientX - rect.left) / trackWidth));
            const newEnd = Math.max(fixedStartMs + 200, Math.min(totalMs, pct * totalMs));
            ov.durationMs = newEnd - fixedStartMs;
            paint();
            renderOverlayLayer();
          };
          const onUp = () => {
            window.removeEventListener("pointermove", onMove);
            window.removeEventListener("pointerup", onUp);
          };
          window.addEventListener("pointermove", onMove);
          window.addEventListener("pointerup", onUp);
        });

        row.appendChild(clip);
        overlayTracks.appendChild(row);
      }
    }

    function bindHandleDrag(handle: HTMLElement, which: "start" | "end") {
      handle.addEventListener("pointerdown", (e) => {
        e.preventDefault();
        handle.setPointerCapture(e.pointerId);
        videoEl.pause();
        const onMove = (ev: PointerEvent) => {
          const pct = pctFromClientX(ev.clientX);
          const time = (pct / 100) * duration;
          const MIN_GAP = 0.3;
          if (which === "start") trimStart = Math.min(time, trimEnd - MIN_GAP);
          else trimEnd = Math.max(time, trimStart + MIN_GAP);
          trimStart = Math.max(0, trimStart);
          trimEnd = Math.min(duration, trimEnd);
          videoEl.currentTime = which === "start" ? trimStart : trimEnd;
          renderTrim();
        };
        const onUp = () => {
          window.removeEventListener("pointermove", onMove);
          window.removeEventListener("pointerup", onUp);
        };
        window.addEventListener("pointermove", onMove);
        window.addEventListener("pointerup", onUp);
      });
    }
    bindHandleDrag(trimStartHandle, "start");
    bindHandleDrag(trimEndHandle, "end");

    // ---------------- Text overlays ----------------

    /** Applies one overlay's entrance-animation progress to its already-mounted box: the exact
     * same linear ramp math as the ffmpeg filter graph in exportStudioVideo (same start time,
     * same duration, same "fade" alpha ramp / "slide-up" travel distance as a fraction of the
     * frame height), so what plays in the preview is a true match for what gets burned into the
     * exported file, not just a similar-looking approximation. */
    /** How a box is anchored to its own xPct/yPct point: centered by default, or hugging one
     * edge for a left/right-aligned lower-third caption, so the text grows away from its anchor
     * rather than always centering on it. */
    function alignTranslatePrefix(ov: TextOverlay): string {
      if (ov.align === "left") return "translate(0%, -50%)";
      if (ov.align === "right") return "translate(-100%, -50%)";
      return "translate(-50%, -50%)";
    }

    function applyOverlayAnimation(box: HTMLElement, ov: TextOverlay, nowMs: number) {
      const entrance = ov.entrance ?? "none";
      const durMs = Math.max(50, ov.entranceDurationMs ?? 350);
      const p = entrance === "none" ? 1 : Math.max(0, Math.min(1, (nowMs - ov.startMs) / durMs));
      const base = alignTranslatePrefix(ov);
      if (entrance === "fade") {
        box.style.opacity = String(p);
        box.style.transform = base;
      } else if (entrance === "slide-up") {
        box.style.opacity = "1";
        const frameHeightPx = stage.getBoundingClientRect().height || 400;
        const offsetPx = (1 - p) * (frameHeightPx * 0.06);
        box.style.transform = `${base} translateY(${offsetPx}px)`;
      } else if (entrance === "pop") {
        // Same popScale/popOpacity curve buildOverlayPngs bakes into the real export frames.
        box.style.opacity = String(popOpacity(p));
        box.style.transform = `${base} scale(${popScale(p)})`;
      } else if (entrance === "bounce") {
        // Same bounceOffsetPx/bounceOpacity curve buildOverlayPngs bakes into the real export
        // frames; unitPx mirrors the font size the export path scales its own offset by.
        const stageWidthPx = stage.getBoundingClientRect().width || 400;
        const unitPx = (ov.sizePct / 100) * stageWidthPx;
        box.style.opacity = String(bounceOpacity(p));
        box.style.transform = `${base} translateY(${bounceOffsetPx(p, unitPx)}px)`;
      } else {
        box.style.opacity = "1";
        box.style.transform = base;
      }
    }

    /** Builds a caption's on-screen content for one instant in time: plain text normally, or,
     * for a word-highlight/type-on template, a live readout of exactly which words should be
     * visible or lit up right now, using that caption's own per-word timing. Falls back to the
     * whole line whenever a caption has no word timing (e.g. its text was hand-typed or edited
     * in the Transcript tab), so editing never leaves a caption broken. */
    function buildCaptionContent(ov: TextOverlay, nowMs: number): (string | HTMLElement)[] {
      const nowSec = nowMs / 1000;
      const words = ov.words;
      if (ov.wordMode === "word-highlight" && words && words.length > 0) {
        return [
          el(
            "span",
            {},
            words.map((w, i) => {
              const active = nowSec >= w.startSec && nowSec < w.endSec;
              const wordText = ov.uppercase ? w.text.toUpperCase() : w.text;
              return el("span", { style: `color:${active ? ov.highlightColor ?? "#e86f00" : ov.color}` }, [
                i === 0 ? wordText : ` ${wordText}`,
              ]);
            })
          ),
        ];
      }
      if (ov.wordMode === "type-on" && words && words.length > 0) {
        const visible = words.filter((w) => nowSec >= w.startSec).map((w) => (ov.uppercase ? w.text.toUpperCase() : w.text));
        return [visible.join(" ") || " "];
      }
      const text = ov.text || "Text";
      return [ov.uppercase ? text.toUpperCase() : text];
    }

    function renderOverlayLayer() {
      clear(overlayLayer);
      for (const ov of overlays) {
        const font = fontById(ov.fontId);
        const isImage = ov.kind === "image" && ov.imageSrc;
        const nowMsInit = videoEl.currentTime * 1000;
        const box = el(
          "div",
          {
            class: `studio-video-overlay-box${ov.id === selectedId ? " selected" : ""}${isImage ? " studio-video-overlay-box-image" : ""}`,
            "data-overlay-id": ov.id,
          },
          isImage ? [el("img", { src: ov.imageSrc!, draggable: "false", alt: "" })] : buildCaptionContent(ov, nowMsInit)
        );
        box.style.left = `${ov.xPct}%`;
        box.style.top = `${ov.yPct}%`;
        if (isImage) {
          // sizePct here is the overlay's own width as a percent of the frame's width; height
          // follows from the image's real aspect ratio so it never looks squashed.
          box.style.width = `${ov.sizePct}%`;
          box.style.aspectRatio = ov.imageAspect ? String(ov.imageAspect) : "1";
        } else {
          box.style.color = ov.color;
          box.style.fontFamily = font.family;
          box.style.fontWeight = ov.bold ? "700" : "400";
          box.style.fontSize = `${ov.sizePct}cqw`;
          box.style.textAlign = ov.align ?? "center";
          if (ov.bgColor) {
            box.style.background = ov.bgColor;
            box.style.padding = "0.3em 0.6em";
            box.style.borderRadius = "0.35em";
            box.style.whiteSpace = "normal";
          } else {
            box.style.background = "";
            box.style.padding = "";
            box.style.borderRadius = "";
          }
        }
        // Outside its own time window, this overlay stays out of the live preview (it still
        // exists on the timeline and stays editable there), matching what the real export will
        // actually burn into the frame.
        const nowMs = videoEl.currentTime * 1000;
        box.style.display = nowMs >= ov.startMs && nowMs <= ov.startMs + ov.durationMs ? "" : "none";
        applyOverlayAnimation(box, ov, nowMs);
        box.addEventListener("pointerdown", (e) => {
          e.preventDefault();
          // Selecting must not rebuild the overlay boxes here, the pointer is down on this
          // exact element and a full remount would detach it mid-drag (real bug caught via
          // testing: setPointerCapture threw InvalidStateError because this node had already
          // been replaced by the time it ran).
          selectOverlayInPlace(ov.id);
          box.setPointerCapture(e.pointerId);
          const onMove = (ev: PointerEvent) => {
            const rect = overlayLayer.getBoundingClientRect();
            if (rect.width === 0 || rect.height === 0) return;
            ov.xPct = Math.max(0, Math.min(100, ((ev.clientX - rect.left) / rect.width) * 100));
            ov.yPct = Math.max(0, Math.min(100, ((ev.clientY - rect.top) / rect.height) * 100));
            box.style.left = `${ov.xPct}%`;
            box.style.top = `${ov.yPct}%`;
          };
          const onUp = () => {
            window.removeEventListener("pointermove", onMove);
            window.removeEventListener("pointerup", onUp);
          };
          window.addEventListener("pointermove", onMove);
          window.addEventListener("pointerup", onUp);
        });
        overlayLayer.appendChild(box);
      }
    }

    function renderOverlayList() {
      clear(overlayListHost);
      if (overlays.length === 0) {
        overlayListHost.appendChild(el("p", { class: "control-hint" }, ["Nothing added on this clip yet."]));
        return;
      }
      for (const ov of overlays) {
        const label = ov.kind === "image" ? ov.text || "Image" : ov.text || "(empty text)";
        const row = el("button", { type: "button", class: `studio-video-overlay-item${ov.id === selectedId ? " active" : ""}` }, [label]);
        row.addEventListener("click", () => selectOverlay(ov.id));
        overlayListHost.appendChild(row);
      }
    }

    function renderProps() {
      clear(propsHost);
      const ov = overlays.find((o) => o.id === selectedId);
      if (!ov) return;

      // Numeric timing fields are shared by every overlay kind, built once here and reused
      // below by whichever branch (image vs. text/sticker) runs.
      const startInput = el("input", { type: "number", min: "0", step: "0.1", value: (ov.startMs / 1000).toFixed(1) }) as HTMLInputElement;
      const durInput = el("input", { type: "number", min: "0.2", step: "0.1", value: (ov.durationMs / 1000).toFixed(1) }) as HTMLInputElement;
      startInput.addEventListener("change", () => {
        const totalMs = duration * 1000;
        const newStart = Math.max(0, Math.min(totalMs - 200, Number(startInput.value) * 1000 || 0));
        ov.startMs = newStart;
        ov.durationMs = Math.min(ov.durationMs, totalMs - newStart);
        durInput.value = (ov.durationMs / 1000).toFixed(1);
        renderOverlayLayer();
        renderOverlayTracks();
      });
      durInput.addEventListener("change", () => {
        const totalMs = duration * 1000;
        ov.durationMs = Math.max(200, Math.min(totalMs - ov.startMs, Number(durInput.value) * 1000 || 200));
        durInput.value = (ov.durationMs / 1000).toFixed(1);
        renderOverlayLayer();
        renderOverlayTracks();
      });
      const timingRow = el("div", { class: "studio-field-row" }, [
        el("label", { class: "studio-field" }, [el("span", {}, ["Starts at (s)"]), startInput]),
        el("label", { class: "studio-field" }, [el("span", {}, ["Lasts (s)"]), durInput]),
      ]);

      // The entrance-animation picker: real, burned-in-at-export styles (see exportStudioVideo's
      // ffmpeg filter graph), not a live-preview-only effect, shared by every overlay kind so a
      // caption, a manual text box, and an image overlay can all animate in the same way.
      const entranceSelect = el(
        "select",
        { class: "studio-field-input" },
        ENTRANCE_OPTIONS.map((o) => el("option", { value: o.id, selected: o.id === (ov.entrance ?? "none") ? "" : undefined }, [o.label]))
      ) as HTMLSelectElement;
      entranceSelect.value = ov.entrance ?? "none";
      entranceSelect.addEventListener("change", () => {
        ov.entrance = entranceSelect.value as TextOverlay["entrance"];
        renderOverlayLayer();
      });
      const entranceRow = el("label", { class: "studio-field" }, [el("span", {}, ["Entrance animation"]), entranceSelect]);

      const deleteBtn = el("button", { type: "button", class: "studio-icon-btn" }, ["Delete overlay"]);
      deleteBtn.addEventListener("click", () => {
        overlays = overlays.filter((o) => o.id !== ov.id);
        selectedId = overlays[0]?.id ?? null;
        renderOverlayLayer();
        renderOverlayList();
        renderProps();
        renderOverlayTracks();
      });

      if (ov.kind === "image") {
        const sizeInput = el("input", { type: "range", min: "5", max: "100", step: "1", value: String(ov.sizePct) }) as HTMLInputElement;
        sizeInput.addEventListener("input", () => {
          ov.sizePct = Number(sizeInput.value);
          renderOverlayLayer();
        });
        const vectorizeBtn = el("button", { type: "button", class: "studio-icon-btn" }, ["Vectorize"]);
        vectorizeBtn.addEventListener("click", () => vectorizeOverlayImage(ov, vectorizeBtn));
        propsHost.append(
          el("label", { class: "studio-field" }, [el("span", {}, ["Size"]), sizeInput]),
          timingRow,
          entranceRow,
          vectorizeBtn,
          deleteBtn
        );
        return;
      }

      const textArea = el("textarea", { class: "studio-field-input", rows: "2" }) as HTMLTextAreaElement;
      textArea.value = ov.text;
      textArea.addEventListener("input", () => {
        ov.text = textArea.value;
        // A hand-edited correction can no longer be trusted to line up with the original
        // per-word timing, so this drops it rather than risk a word-highlight that no longer
        // matches what's actually on screen.
        ov.words = undefined;
        renderOverlayLayer();
        renderOverlayList();
        renderOverlayTracks();
      });

      const fontSelect = el(
        "select",
        { class: "studio-field-input" },
        OVERLAY_FONTS.map((f) => el("option", { value: f.id, selected: f.id === ov.fontId ? "" : undefined }, [f.label]))
      ) as HTMLSelectElement;
      fontSelect.value = ov.fontId;
      fontSelect.addEventListener("change", () => {
        ov.fontId = fontSelect.value;
        renderOverlayLayer();
      });

      const sizeInput = el("input", { type: "range", min: "2", max: "16", step: "0.5", value: String(ov.sizePct) }) as HTMLInputElement;
      sizeInput.addEventListener("input", () => {
        ov.sizePct = Number(sizeInput.value);
        renderOverlayLayer();
      });

      const colorInput = el("input", { type: "color", value: ov.color }) as HTMLInputElement;
      colorInput.addEventListener("input", () => {
        ov.color = colorInput.value;
        renderOverlayLayer();
      });

      const boldBtn = el("button", { type: "button", class: `studio-toggle-btn${ov.bold ? " active" : ""}` }, ["Bold"]);
      boldBtn.addEventListener("click", () => {
        ov.bold = !ov.bold;
        boldBtn.classList.toggle("active", ov.bold);
        renderOverlayLayer();
      });

      const alignSelect = el(
        "select",
        { class: "studio-field-input" },
        [
          el("option", { value: "center", selected: (ov.align ?? "center") === "center" ? "" : undefined }, ["Center"]),
          el("option", { value: "left", selected: ov.align === "left" ? "" : undefined }, ["Left"]),
          el("option", { value: "right", selected: ov.align === "right" ? "" : undefined }, ["Right"]),
        ]
      ) as HTMLSelectElement;
      alignSelect.value = ov.align ?? "center";
      alignSelect.addEventListener("change", () => {
        ov.align = alignSelect.value as TextOverlay["align"];
        renderOverlayLayer();
      });

      const uppercaseBtn = el("button", { type: "button", class: `studio-toggle-btn${ov.uppercase ? " active" : ""}` }, ["UPPERCASE"]);
      uppercaseBtn.addEventListener("click", () => {
        ov.uppercase = !ov.uppercase;
        uppercaseBtn.classList.toggle("active", ov.uppercase);
        renderOverlayLayer();
      });

      propsHost.append(
        el("label", { class: "studio-field" }, [el("span", {}, ["Text"]), textArea]),
        el("label", { class: "studio-field" }, [el("span", {}, ["Font"]), fontSelect]),
        el("label", { class: "studio-field" }, [el("span", {}, ["Size"]), sizeInput]),
        el("label", { class: "studio-field" }, [el("span", {}, ["Color"]), colorInput]),
        el("label", { class: "studio-field" }, [el("span", {}, ["Align"]), alignSelect]),
        timingRow,
        entranceRow,
        boldBtn,
        uppercaseBtn
      );

      // Word-level fields only make sense on an auto-generated caption that still has its
      // per-word timing intact (a hand-typed overlay, or a caption whose text was hand-edited,
      // has nothing to key the animation off).
      if (ov.isCaption && ov.words && ov.words.length > 0) {
        const wordModeSelect = el(
          "select",
          { class: "studio-field-input" },
          [
            el("option", { value: "none", selected: !ov.wordMode || ov.wordMode === "none" ? "" : undefined }, ["None"]),
            el("option", { value: "type-on", selected: ov.wordMode === "type-on" ? "" : undefined }, ["Typewriter (word by word)"]),
            el("option", { value: "word-highlight", selected: ov.wordMode === "word-highlight" ? "" : undefined }, ["Karaoke highlight"]),
          ]
        ) as HTMLSelectElement;
        wordModeSelect.value = ov.wordMode ?? "none";
        wordModeSelect.addEventListener("change", () => {
          ov.wordMode = wordModeSelect.value as TextOverlay["wordMode"];
          renderOverlayLayer();
        });
        const highlightColorInput = el("input", { type: "color", value: ov.highlightColor ?? "#e86f00" }) as HTMLInputElement;
        highlightColorInput.addEventListener("input", () => {
          ov.highlightColor = highlightColorInput.value;
          renderOverlayLayer();
        });
        propsHost.append(
          el("label", { class: "studio-field" }, [el("span", {}, ["Word animation"]), wordModeSelect]),
          el("label", { class: "studio-field" }, [el("span", {}, ["Highlight color"]), highlightColorInput])
        );
      }

      propsHost.appendChild(deleteBtn);
    }

    /** Selecting an overlay/caption/sticker/image on the canvas should also bring its editing
     * controls into view: if some other component's panel is open, switch to the tab matching
     * what was just selected (the shared list/props host all four use), leaving it alone if any
     * of the four is already open. */
    function focusOverlayComponent(ov?: TextOverlay) {
      if (ov?.isCaption && captionSubTab !== "captions") {
        captionSubTab = "captions";
        if (activeComponent === "captions") {
          renderComponentPanel();
          return;
        }
      }
      if (activeComponent === "text" || activeComponent === "captions" || activeComponent === "image" || activeComponent === "stickers") return;
      openComponent(ov?.isCaption ? "captions" : ov?.kind === "image" ? "image" : ov?.kind === "sticker" ? "stickers" : "text");
    }

    function selectOverlay(id: string) {
      selectedId = id;
      renderOverlayLayer();
      focusOverlayComponent(overlays.find((o) => o.id === id));
      renderOverlayList();
      renderProps();
      renderOverlayTracks();
    }

    /** Same selection state as selectOverlay, but toggles the "selected"/"active" classes on
     * the existing overlay boxes and timeline clips instead of rebuilding them, so it is safe
     * to call from a box's or a timeline clip's own pointerdown handler right before (or during)
     * a drag on that exact element. Rebuilding here, as selectOverlay does, would destroy and
     * recreate the very node the pointer just went down on, which throws
     * InvalidStateError the moment the drag then tries to setPointerCapture on it, a real bug
     * caught by testing both the canvas-box drag and, later, the timeline-clip drag. */
    function selectOverlayInPlace(id: string) {
      selectedId = id;
      overlayLayer.querySelectorAll(".studio-video-overlay-box").forEach((node) => {
        node.classList.toggle("selected", node.getAttribute("data-overlay-id") === id);
      });
      overlayTracks.querySelectorAll(".studio-video-layer-row").forEach((node) => {
        node.classList.toggle("active", node.getAttribute("data-overlay-id") === id);
      });
      focusOverlayComponent(overlays.find((o) => o.id === id));
      renderOverlayList();
      renderProps();
    }

    addTextBtn.addEventListener("click", () => {
      const [startMs, durationMs] = defaultOverlayWindowMs();
      const ov: TextOverlay = {
        id: uid(), text: "Your text", xPct: 50, yPct: 80, sizePct: 6, color: "#ffffff", fontId: "anton", bold: true,
        startMs, durationMs,
      };
      overlays.push(ov);
      selectOverlay(ov.id);
    });

    /** A newly added overlay starts at the current playhead and runs for a short, editable
     * default span (or the rest of the clip if there's less than that left), rather than
     * silently spanning the whole video, so a fresh overlay always shows up as its own
     * independent clip on the timeline, ready to be dragged. */
    function defaultOverlayWindowMs(): [number, number] {
      const total = duration > 0 ? duration * 1000 : 0;
      const start = Math.max(0, videoEl.currentTime * 1000);
      const defaultSpan = 3000;
      const remaining = total > 0 ? Math.max(500, total - start) : defaultSpan;
      return [Math.min(start, Math.max(0, total - 500)), Math.min(defaultSpan, remaining)];
    }

    // ---------------- Export ----------------

    // Shared with applyOverlayAnimation's live preview so the export burns in the exact same
    // curve someone saw while editing, not just a similar-looking approximation.
    function popScale(p: number): number {
      const overshoot = p < 1 ? 1 + Math.sin(p * Math.PI) * 0.35 * (1 - p) : 1;
      return Math.max(0.05, 0.5 + 0.5 * p * overshoot);
    }
    function popOpacity(p: number): number {
      return Math.min(1, p * 2.5);
    }
    function bounceOffsetPx(p: number, unitPx: number): number {
      const settle = (1 - p) * unitPx * 0.9;
      const wobble = p < 1 ? Math.sin(p * Math.PI * 3.2) * (1 - p) * unitPx * 0.6 : 0;
      return settle - wobble;
    }
    function bounceOpacity(p: number): number {
      return Math.min(1, p * 3);
    }

    /** Draws one overlay's real content (image or text/caption) onto an already-sized,
     * already-cleared canvas, honoring that overlay's own alignment, uppercasing, and
     * background pill, exactly as the live preview does. `atSec`, when given, picks which
     * words are lit up/visible for a word-highlight or type-on caption at that instant; a
     * `scale`/`translateYPx`/`opacityOverride` let the pop/bounce frame sequence below bake a
     * real, non-animated scale or offset straight into the pixels of one still frame. */
    async function paintOverlayFrame(
      ctx: CanvasRenderingContext2D,
      width: number,
      height: number,
      ov: TextOverlay,
      opts: { atSec?: number; scale?: number; translateYPx?: number; opacityOverride?: number } = {}
    ): Promise<void> {
      ctx.save();
      ctx.globalAlpha = opts.opacityOverride ?? 1;
      const cx = (ov.xPct / 100) * width;
      const cy = (ov.yPct / 100) * height + (opts.translateYPx ?? 0);
      if (opts.scale && opts.scale !== 1) {
        ctx.translate(cx, cy);
        ctx.scale(opts.scale, opts.scale);
        ctx.translate(-cx, -cy);
      }

      if (ov.kind === "image" && ov.imageSrc) {
        const img = new Image();
        await new Promise<void>((resolve) => {
          img.onload = () => resolve();
          img.onerror = () => resolve();
          img.src = ov.imageSrc!;
        });
        const boxW = (ov.sizePct / 100) * width;
        const boxH = boxW / (ov.imageAspect || img.width / Math.max(1, img.height) || 1);
        if (img.width && img.height) ctx.drawImage(img, cx - boxW / 2, cy - boxH / 2, boxW, boxH);
        ctx.restore();
        return;
      }

      const font = fontById(ov.fontId);
      const sizePx = Math.max(10, Math.round((ov.sizePct / 100) * width));
      const weight = ov.bold ? "700" : "400";
      try {
        await document.fonts.load(`${weight} ${sizePx}px "${font.canvasFamily}"`);
      } catch {
        // Font failed to preload, canvas falls back to the platform default rather than blocking export.
      }
      ctx.font = `${ov.bold ? "bold " : ""}${sizePx}px "${font.canvasFamily}", sans-serif`;
      ctx.textBaseline = "middle";
      const align = ov.align ?? "center";

      // Build the word/color segments for this instant: word-highlight lights up whichever
      // word is being spoken right now, type-on reveals only the words said so far, and
      // everything else just shows the whole (optionally uppercased) line as one segment.
      let segments: { text: string; color: string }[];
      if (ov.wordMode === "word-highlight" && ov.words && ov.words.length > 0 && opts.atSec !== undefined) {
        segments = ov.words.map((w) => ({
          text: ov.uppercase ? w.text.toUpperCase() : w.text,
          color: opts.atSec! >= w.startSec && opts.atSec! < w.endSec ? ov.highlightColor ?? "#e86f00" : ov.color,
        }));
      } else if (ov.wordMode === "type-on" && ov.words && ov.words.length > 0 && opts.atSec !== undefined) {
        segments = ov.words
          .filter((w) => opts.atSec! >= w.startSec)
          .map((w) => ({ text: ov.uppercase ? w.text.toUpperCase() : w.text, color: ov.color }));
      } else {
        segments = [{ text: ov.uppercase ? (ov.text || "").toUpperCase() : ov.text || "", color: ov.color }];
      }

      const spaceWidth = ctx.measureText(" ").width;
      const widths = segments.map((s) => ctx.measureText(s.text).width);
      const totalWidth = widths.reduce((a, b) => a + b, 0) + spaceWidth * Math.max(0, segments.length - 1);
      let startX = cx;
      if (align === "left") ctx.textAlign = "left";
      else if (align === "right") {
        ctx.textAlign = "left";
        startX = cx - totalWidth;
      } else {
        ctx.textAlign = "left";
        startX = cx - totalWidth / 2;
      }

      if (ov.bgColor && totalWidth > 0) {
        const padX = sizePx * 0.4;
        const padY = sizePx * 0.35;
        const boxH = sizePx + padY * 2;
        const boxX = startX - padX;
        const boxY = cy - boxH / 2;
        const boxW = totalWidth + padX * 2;
        const radius = Math.min(boxH / 2, 18);
        ctx.fillStyle = ov.bgColor;
        ctx.beginPath();
        ctx.moveTo(boxX + radius, boxY);
        ctx.arcTo(boxX + boxW, boxY, boxX + boxW, boxY + boxH, radius);
        ctx.arcTo(boxX + boxW, boxY + boxH, boxX, boxY + boxH, radius);
        ctx.arcTo(boxX, boxY + boxH, boxX, boxY, radius);
        ctx.arcTo(boxX, boxY, boxX + boxW, boxY, radius);
        ctx.closePath();
        ctx.fill();
      }

      let penX = startX;
      for (let i = 0; i < segments.length; i++) {
        ctx.fillStyle = segments[i].color;
        ctx.fillText(segments[i].text, penX, cy);
        penX += widths[i] + spaceWidth;
      }
      ctx.restore();
    }

    async function canvasToPng(canvas: HTMLCanvasElement): Promise<Blob | undefined> {
      return new Promise((resolve) => canvas.toBlob((blob) => resolve(blob ?? undefined), "image/png"));
    }

    /** One transparent PNG per overlay for the plain case (no per-word content changes, no
     * pop/bounce scale), paired with that overlay's own time window, exactly as before: the
     * fade/slide-up entrances stay a pure, already-verified ffmpeg filter effect rather than a
     * frame sequence, since they only ever animate opacity/position, never the pixels
     * themselves. Overlays whose *content* changes over time (a karaoke or typewriter caption)
     * or whose entrance is a scale/bounce (which the ffmpeg overlay filter can't express)
     * instead get a short sequence of real, separately-timed PNGs, one per word or per
     * animation step, each one truly baked with that instant's own pixels; ffmpeg then plays
     * them back to back exactly like it already does for any other set of timed layers. */
    async function buildOverlayPngs(): Promise<TimedOverlayLayer[]> {
      const width = videoEl.videoWidth;
      const height = videoEl.videoHeight;
      if (!width || !height) return [];

      const layers: TimedOverlayLayer[] = [];
      const FRAME_STEP_SEC = 0.08; // ~12 discrete frames/sec for a baked scale or bounce animation, smooth enough, cheap enough to render client-side

      for (const ov of overlays) {
        const startSec = ov.startMs / 1000;
        const endSec = (ov.startMs + ov.durationMs) / 1000;
        const hasWordFrames = ov.kind !== "image" && ov.wordMode && ov.wordMode !== "none" && !!ov.words && ov.words.length > 0;
        const hasScaleFrames = ov.entrance === "pop" || ov.entrance === "bounce";

        const newCanvas = () => {
          const c = document.createElement("canvas");
          c.width = width;
          c.height = height;
          return c;
        };

        if (hasWordFrames) {
          const words = ov.words!;
          const boundaries = Array.from(
            new Set<number>([startSec, ...words.map((w) => w.startSec), ...words.map((w) => w.endSec), endSec])
          )
            .filter((t) => t >= startSec && t <= endSec)
            .sort((a, b) => a - b);
          for (let i = 0; i < boundaries.length - 1; i++) {
            const segStart = boundaries[i];
            const segEnd = boundaries[i + 1];
            if (segEnd - segStart < 0.02) continue;
            const canvas = newCanvas();
            const ctx = canvas.getContext("2d");
            if (!ctx) continue;
            await paintOverlayFrame(ctx, width, height, ov, { atSec: (segStart + segEnd) / 2 });
            const png = await canvasToPng(canvas);
            if (png) layers.push({ png, startSec: segStart, endSec: segEnd, entrance: "none" });
          }
          continue;
        }

        if (hasScaleFrames) {
          const fontSizePx = Math.max(10, Math.round((ov.sizePct / 100) * width));
          const durSec = Math.max(0.05, Math.min(endSec - startSec, (ov.entranceDurationMs ?? 400) / 1000));
          const steps = Math.max(4, Math.round(durSec / FRAME_STEP_SEC));
          for (let i = 0; i < steps; i++) {
            const p = (i + 0.5) / steps;
            const canvas = newCanvas();
            const ctx = canvas.getContext("2d");
            if (!ctx) continue;
            if (ov.entrance === "pop") {
              await paintOverlayFrame(ctx, width, height, ov, { scale: popScale(p), opacityOverride: popOpacity(p) });
            } else {
              await paintOverlayFrame(ctx, width, height, ov, {
                translateYPx: bounceOffsetPx(p, fontSizePx),
                opacityOverride: bounceOpacity(p),
              });
            }
            const png = await canvasToPng(canvas);
            if (png) layers.push({ png, startSec: startSec + (i / steps) * durSec, endSec: startSec + ((i + 1) / steps) * durSec, entrance: "none" });
          }
          if (endSec > startSec + durSec) {
            const canvas = newCanvas();
            const ctx = canvas.getContext("2d");
            if (ctx) {
              await paintOverlayFrame(ctx, width, height, ov, {});
              const png = await canvasToPng(canvas);
              if (png) layers.push({ png, startSec: startSec + durSec, endSec, entrance: "none" });
            }
          }
          continue;
        }

        // The plain path: unchanged from before, still the exact filter-graph-verified
        // fade/slide-up/none entrance.
        const canvas = newCanvas();
        const ctx = canvas.getContext("2d");
        if (!ctx) continue;
        await paintOverlayFrame(ctx, width, height, ov, {});
        const png = await canvasToPng(canvas);
        if (png) {
          layers.push({
            png,
            startSec,
            endSec,
            // pop/bounce never reach this path (hasScaleFrames catches them above), so this is
            // always "none", "fade", or "slide-up", the three ffmpeg-filter-native entrances.
            entrance: ov.entrance === "fade" || ov.entrance === "slide-up" ? ov.entrance : "none",
            entranceDurationSec: Math.max(0.05, (ov.entranceDurationMs ?? 350) / 1000),
          });
        }
      }
      return layers;
    }

    exportBtn.onclick = async () => {
      if (getUsageStatus().atLimit) {
        clear(resultHost);
        resultHost.appendChild(usageLimitReachedPanel());
        return;
      }
      clear(resultHost);
      const process = createProcessPanel(["Reading file", "Rendering", "Finalizing"]);
      resultHost.appendChild(process.root);
      const startedAt = performance.now();
      try {
        const overlayLayers = await buildOverlayPngs();
        const filterFragment = videoFilterById(filterPresetId).ffmpegFilter || undefined;
        const result = await exportStudioVideo(
          file,
          {
            startSec: trimStart,
            endSec: trimEnd > trimStart ? trimEnd : duration,
            overlays: overlayLayers,
            filterPreset: filterFragment,
            audioGainDb: audioGainDb !== 0 ? audioGainDb : undefined,
          },
          ({ phase, ratio }) => {
            process.setStep(phase);
            process.setProgress(ratio ?? null);
          }
        );
        recordCompletedOperation();
        const previewUrl = URL.createObjectURL(result.blob);
        clear(resultHost);
        resultHost.appendChild(
          renderResultPanel({
            previewUrl,
            previewIsVideo: true,
            outputName: result.outputName,
            outputFormatLabel: "MP4 (H.264)",
            originalBytes: file.size,
            outputBytes: result.blob.size,
            processingMs: performance.now() - startedAt,
            blob: result.blob,
            honestyNote: "Re-encoded with libx264 so the trim and any overlays land exactly, not a lossless stream copy.",
            onRunAnother: () => renderUpload(),
          })
        );
      } catch (err) {
        console.error("Studio video export failed:", err);
        clear(resultHost);
        resultHost.appendChild(
          el("div", { class: "validation-error" }, [
            el("strong", {}, ["Something went wrong. "]),
            err instanceof Error ? err.message : String(err),
          ])
        );
      }
    };

    renderTrim();
    renderOverlayLayer();
    renderOverlayList();
  }

  if (opts.autoLoadVideoUrl) {
    renderUpload();
    fetch(opts.autoLoadVideoUrl)
      .then((r) => r.blob())
      .then((blob) => openEditor(new File([blob], "demo-clip.mp4", { type: blob.type || "video/mp4" })))
      .catch(() => {
        // The guided tour degrades gracefully to the plain upload screen if this ever fails.
      });
  } else {
    renderUpload();
  }
  return root;
}
